### ISSUE TITLE
Setup Circle CI pipline

### ISSUE THREAD

**Issue by Joseph455** [Computer-Science-dev-group/Django-Backend#8]
setup a job to do the following:

- Test installation
- Static testing job {pre-commit}
- unit-testing job {pytest with test coverage} {90% test coverage}

sample circle-ci.yml file
```
version: 2.2
jobs:
    build:
        docker:
            - image: cimg/python:3.10.4
        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "./backend/requirements.txt" }}
            - run:
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r ./backend/requirements.txt
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "./backend/requirements.txt" }}
                paths:
                    - "venv"
            - run:
                name: Runing static tests
                command: |
                    . venv/bin/activate
                    pre-commit run --all-files
            - run:
                name: Running unit tests
                command: |
                    . venv/bin/activate
                    cd ./backend/
                    pytest
            - store_artifacts:
                path: test-reports/
                destination: oshs-ci
```
